#from . import account_move_inherit
#from . import project_task_inherit
#from . import project_task_line
from . import merge_device
#from . import merge_device_os
#from . import product_template_inherit
#from . import product_brand
#from . import stock_location_inherit
from . import fleet_vehicle_inherit
#from . import fleet_vehicle_line
#from . import sale_order_inherit